# Generated by Django 2.1.7 on 2019-04-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pagesmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesmodel',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
