# Generated by Django 2.1.7 on 2019-04-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190401_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagesmodel',
            old_name='Image',
            new_name='Image1',
        ),
        migrations.RemoveField(
            model_name='pagesmodel',
            name='body',
        ),
        migrations.AddField(
            model_name='pagesmodel',
            name='About',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='pagesmodel',
            name='Footer',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='pagesmodel',
            name='Image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='pagesmodel',
            name='Image3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='pagesmodel',
            name='mainHeader',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='pagesmodel',
            name='subHeader',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
