# Generated by Django 2.1.7 on 2019-04-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190403_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesmodel',
            name='About',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='pagesmodel',
            name='Footer',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
    ]
