# Generated by Django 2.1.7 on 2019-04-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190407_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexmodel',
            name='bannerImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
