# Generated by Django 2.1.7 on 2019-04-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190407_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexmodel',
            name='indexFeaturedImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
