# Generated by Django 2.1.7 on 2019-04-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190407_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexmodel',
            name='indexFeaturedh4',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
