# Generated by Django 2.1.7 on 2019-04-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_indexmodel_indexfeaturedh4'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexmodel',
            name='footerLink',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='indexmodel',
            name='footerLinkText',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='indexmodel',
            name='footerTitle',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='indexmodel',
            name='footerTitle2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='indexmodel',
            name='footerp1',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
