# Generated by Django 2.1.7 on 2019-04-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190407_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexmodel',
            name='indirectLink1Text',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='indexmodel',
            name='indirectLink2Text',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='indexmodel',
            name='indirectLink3Text',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='indexmodel',
            name='indirectLink4Text',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='indexmodel',
            name='indirectLink5Text',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='indexmodel',
            name='indirectLink6Text',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='indexmodel',
            name='indirectLink7Text',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
