# Generated by Django 2.1.7 on 2019-04-07 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20190407_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagesmodel',
            name='link8',
        ),
        migrations.RemoveField(
            model_name='pagesmodel',
            name='link8text',
        ),
    ]
