# Generated by Django 2.1.7 on 2019-04-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20190407_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesmodel',
            name='link8',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='pagesmodel',
            name='link8text',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
